name: scyject
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sqflite_sqlcipher: ^2.1.0 
  equatable: ^2.0.5 
  dartz: ^0.10.0-nullsafety.2
  flutter_bloc: ^8.0.0
  get_it: ^7.1.3
  intl: ^0.17.0
  flutter_svg: ^1.1.5
  provider: ^6.0.2






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

