name: scyject
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  intl: ^0.17.0
  flutter_svg: ^1.1.5
  provider: ^6.0.2
  firebase_database: ^10.0.3
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  flutter_slidable: ^2.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

