// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArgNbol3mMrVotFUqVA6UpZoCg1IosViU',
    appId: '1:572149479964:web:8f7da787295cfb7acdbdd9',
    messagingSenderId: '572149479964',
    projectId: 'scyject',
    authDomain: 'scyject.firebaseapp.com',
    storageBucket: 'scyject.appspot.com',
    measurementId: 'G-61SRH9GWSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjVwLZ7d8JcqZOOR-sUkLstWM2Y5eXyII',
    appId: '1:572149479964:android:61d3c0b39e5ee626cdbdd9',
    messagingSenderId: '572149479964',
    projectId: 'scyject',
    storageBucket: 'scyject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3d8FwFVamak35IEm8nuDogxH-ldiXw8c',
    appId: '1:572149479964:ios:1717b4bb3b8d86eecdbdd9',
    messagingSenderId: '572149479964',
    projectId: 'scyject',
    storageBucket: 'scyject.appspot.com',
    iosClientId:
        '572149479964-1qpb44ntn9klb4qdmco8gkar3harktod.apps.googleusercontent.com',
    iosBundleId: 'com.example.scyject',
  );
}
